### ISSUE TITLE
Create a PR for java program for permutation by recursion (Leetcode Problem)

### ISSUE THREAD

**Issue by Pandz18** [codedecks-in/LeetCode-Solutions#115]

**Comment by GouravRusiya30** [comment]
@Pandz18 
Can you create an issue for particular leetcode problem ?

**Comment by Pandz18** [comment]
> @Pandz18
> Can you create an issue for particular leetcode problem ?

@GouravRusiya30 , hi , the question is permutations of an array , but I'm using the recursion method

**Comment by GouravRusiya30** [comment]
Directly create a PR

**Comment by Pandz18** [comment]
ok
