### ISSUE TITLE
Request to add contributors list in README file

### ISSUE THREAD

**Issue by Pandz18** [codedecks-in/LeetCode-Solutions#125]

**Comment by GouravRusiya30** [comment]
@Pandz18 It's the responsibility of individuals to edit README and add update contributors list !!!

Closing this un-necessary issue

**Comment by GouravRusiya30** [comment]
Check all the contributors list
https://github.com/codedecks-in/LeetCode-Solutions#contributors

**Comment by Pandz18** [comment]
oh , sorry , I thought I should get your permission to do so
