### ISSUE TITLE
Why don't we unify the file names?

### ISSUE THREAD

**Issue by JeongDaHyeon** [codedecks-in/LeetCode-Solutions#142]
![image](https://user-images.githubusercontent.com/48541114/99071306-3917ac00-25f5-11eb-98c3-d3d8273c079e.png)

File names are different. Would you like to add a rule related to this?

**Comment by GouravRusiya30** [comment]
yes, you are right.

Will you be able to pick this task @JeongDaHyeon

**Comment by JeongDaHyeon** [comment]
Thank you! Have a nice day ~ 😃
