### ISSUE TITLE
Buy and Sell Stock series in Java

### ISSUE THREAD

**Issue by divya1509** [codedecks-in/LeetCode-Solutions#212]
Hey, I want to add the buy and sell stock series. The questions are :
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/

I would provide a well-explanatory solution to each problem with examples.
Please assign me this issue.
Thanks

**Comment by GouravRusiya30** [comment]
Sure Diyya, please go ahead

**Comment by ShadyResurrected** [comment]
Hello , If this issue is still not resolved can you assign it to me

**Comment by GouravRusiya30** [comment]
@ShadyResurrected you can submit respective PRs

**Comment by Anushk2003** [comment]
hey , is this issue still open? if yes can u assign it to me
