### ISSUE TITLE
Count Number of Bad Pairs #2364

### ISSUE THREAD

**Issue by harshagrawal523** [codedecks-in/LeetCode-Solutions#313]
You are given a 0-indexed integer array nums. A pair of indices (i, j) is a bad pair if i < j and j - i != nums[j] - nums[i].

Return the total number of bad pairs in nums.

**Comment by RonitThukral** [comment]
hello! 
I am very new to this open source community. I am interested in solving this problem.

**Comment by gouravjangid5044** [comment]
Please assign this to me
