### ISSUE TITLE
Find The Original Array of Prefix Xor 

### ISSUE THREAD

**Issue by 2tanayk** [codedecks-in/LeetCode-Solutions#325]
I would like to contribute a solution to the problem [Find The Original Array of Prefix Xor](https://leetcode.com/problems/find-the-original-array-of-prefix-xor/)
(topic - bit manipulation)

**Comment by ShubhamRawat28** [comment]
I would like to contribute a solution to the problem [Find The Original Array of Prefix Xor](https://leetcode.com/problems/find-the-original-array-of-prefix-xor/)
(topic - bit manipulation)
