### ISSUE TITLE
Generate PR for codedecks by solving any STACK/QUEUE section problem of LeetCode

### ISSUE THREAD

**Issue by GouravRusiya30** [codedecks-in/LeetCode-Solutions#90]
- Do you want to add a New solution ?
- Or you solution is better than already added solution ?

### Then go ahead and create a pull request. Please read [Pull Request Process](https://github.com/codedecks-in/LeetCode-Solutions/blob/master/PULL_REQUEST_PROCESS.md) for simple steps to contribute

- [STACK](https://leetcode.com/tag/stack/)

- [QUEUE](https://leetcode.com/tag/queue/)

**Comment by MercerFrey** [comment]
Hey i solve a stack problem with recursion is it fine :)

**Comment by Pandz18** [comment]
> Hey i solve a stack problem with recursion is it fine :)

hey , if you mean permutation using recession method ,I've already pulled a issue for that

**Comment by MercerFrey** [comment]
> hey , if you mean permutation using recession method ,I've already pulled a issue for that

no i literally solved binary search tree problem with recursion but it was categorized as a stack problem in the website

**Comment by Pandz18** [comment]
> > hey , if you mean permutation using recession method ,I've already pulled a issue for that
> 
> no i literally solved binary search tree problem with recursion but it was categorized as a stack problem in the website

oh , ok , idk then , I guess you could pull another issue for it
